name: My First MLOps Pipeline # The name that appears in the GitHub UI

# 1. The Trigger (When should this run?)
on: 
  push:
    branches:
      - main # Only run when code is pushed to the 'main' branch

# 2. The Jobs (What should it do?)
jobs:
  build-and-test: # Name of the job
    runs-on: ubuntu-latest # Tell GitHub to give us a fresh Ubuntu Linux VM
    
    # 3. The Steps (The actual commands to run on the Ubuntu VM)
    steps:
      # Step A: A pre-built action provided by GitHub to copy your code into the VM
      - name: Checkout Code
        uses: actions/checkout@v3 

      # Step B: Running a simple bash command
      - name: Run a Bash Script
        run: |
          echo "Hello from GitHub Actions!"
          echo "This is running on a cloud server."
          
      # Step C: Proving we have access to the code
      - name: List files
        run: ls -la
